spring.application.name=Wallet-Payment-System
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/Wallet_System
spring.datasource.username=postgres
spring.datasource.password=monu1102

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# RabbitMQ connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# SMTP (example using Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alertpaymentwallet@gmail.com
spring.mail.password=pmvpjdegdfxzzlpv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true